version: "3"
services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "5000:5000"
      - "5001:5001"
      - "80:80"
    network_mode: host
  service-1:
    build:
      context: ./service-1
    ports:
      - "5004:5004"
      - "5005:5005"
    labels:
      - "SERVICE_5005_NAME=test-service"
      - "SERVICE_5004_IGNORE=true"
      - "SERVICE_TAGS=test1,test2"
  service-2:
    build:
      context: ./service-2
    ports:
      - "5002:5002"
      - "5003:5003"
    labels:
      - "SERVICE_5003_NAME=test-service"
      - "SERVICE_5002_IGNORE=true"
      - "SERVICE_TAGS=test1,test2"