version: "3"
services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "5000:5000"
      - "5001:5001"
    network_mode: host
  service-1:
    build:
      context: ./service-1
    ports:
      - "5004:5004"
      - "5005:5005"
  service-2:
    build:
      context: ./service-2
    ports:
      - "5002:5002"
      - "5003:5003"